CREATE TABLE rfid_tag (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    id_tag VARCHAR(50) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES user_account(id) ON DELETE CASCADE
);